### ISSUE TITLE
space after NP[str] case.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#107]
![grafik](https://user-images.githubusercontent.com/4655859/110147939-84d8a600-7ddc-11eb-8083-9a5c0fd6671f.png)

There is too few space after NP[str]. I checked the manual but could not find a way to change this.

```latex
\avm{
[head & verb \\
arg-st & <[arg NP![\type{str}]! \\
	   realized $+$]> \+ \2 ]
\impl
[arg-st & <[arg  NP![\type{snom}]!]> \+ \2 ]
}
```

**Comment by kopeckyf** [comment]
Cannot reproduce this error. Please make sure this occurs when all software is up to date. 

![grafik](https://user-images.githubusercontent.com/10461729/111964438-e5622580-8af4-11eb-9c11-ef1a461dab93.png)

**Comment by stefan11** [comment]
There is no alignment in this AVM. I guess the problem is due to this.
