### ISSUE TITLE
Differentiate spelling of Ack. section based on whether AmE or not

### ISSUE THREAD

**Issue by kopeckyf** [langsci/259#110]
(Just a quick info that https://github.com/langsci/langscibook/issues/137 applies to your book project as well.)

In short, the _Acknowledgements_ section in our template is usually spelled as _Acknowledg**e**ments_. As far as I know, all English variants except American English accept this spelling. American English drops the _**e**_, i.e. _Acknowledgments_.

Currently, the only known method to do this correctly (if one wants to, but it may be considered too minor) is manual renaming for all chapters that are written in AmE.

**Comment by stefan11** [comment]
I introduced two commands that are called and insert the right word.
