### ISSUE TITLE
font issue: ldots in text and mathmode differ (order.tex)

### ISSUE THREAD

**Issue by stefan11** [langsci/259#120]
![grafik](https://user-images.githubusercontent.com/4655859/111915884-adb59800-8a78-11eb-84fe-053a9368ad6f.png)

```latex
\avm{
[ dom      & $\delta_0 \bigcirc \delta_1 \bigcirc \ldots \bigcirc \delta_n$\\
  head-dtr & [ dom &  $\delta_0$ ]\\
  non-head-dtrs & <  [ dom &  $\delta_1$ ], \ldots, [ dom &  $\delta_n$ ] > ] 
}
```

Not sure this should/can be fied in langsci-avm.sty. The math font seems to use different \ldots than the normal font. I guess the ones with more space are preferable.

**Comment by kopeckyf** [comment]
Probably due to an outdated version of Libertinus.  In current Libertinus, the ellipsis glyph (U 2026) `…` is equal in Libertinus-Math and Libertinus-Serif. 

Please obtain the newest Libertinus release from https://github.com/alerque/libertinus/releases

**Comment by stefan11** [comment]
> Probably due to an outdated version of Libertinus. In current Libertinus, the ellipsis glyph (U 2026) `…` is equal in Libertinus-Math and Libertinus-Serif.
> 
> Please obtain the newest Libertinus release from https://github.com/alerque/libertinus/releases

Thanks! Do I have to put this in a subdirectory and add somthing to langscibook.cls so that tex finds it?
