### ISSUE TITLE
install new libertinus font

### ISSUE THREAD

**Issue by stefan11** [langsci/259#121]
![grafik](https://user-images.githubusercontent.com/4655859/112355101-a0ddb200-8ccd-11eb-8d14-819c310f9120.png)

The dots in mathmode differ from \ldots in text mode. Felix said that this has been fixed in the new version of the font. But I do not get the font to work with the book. The AVM is in order.tex

**Comment by Glottotopia** [comment]
Libertinus, not Libertine

**Comment by stefan11** [comment]
> Libertinus, not Libertine

OK. Libertuns does not work either.

**Comment by stefan11** [comment]
Duplicate of #120
