### ISSUE TITLE
too much space between two exes with multicolumn and two few space after them cg.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#156]
![grafik](https://user-images.githubusercontent.com/4655859/119522117-0278d600-bd7c-11eb-9472-0dd7f0b40d3c.png)

I could do this with tabular, but this would break the labels.

**Comment by Glottotopia** [comment]
don't use multicolumn. It is never the right solution.
You can use something along the lines of

```
\ea
\parbox[t]{5cm}{
\ea
}%
\parbox[t]{5cm}{
\ex
}
\z
\z
```

(from the top of my head). Don't quote me on the exact positioning of
the \z's

**Comment by stefan11** [comment]
Thanks! I think your solution does not work because of the nesting of \ea within brackets. I tryed the following:
```latex
\eal
\label{SE0}%
\parbox[t]{5cm}{%
\ex\label{rseone} Forward Slash Elimination:\\[.5\baselineskip]
\begin{prooftree}
\NoSem
\hypo{\LexEnt{\pt{\ptv{a}}}{\sem{ }}{\syncat{\textit{A}/\textit{B}}}}
\hypo{\LexEnt{\pt{\ptv{b}}}{\sem{ }}{\syncat{\textit{B}}}}
\infer2[\ensuremath{/}E]{\LexEnt{\pt{\ptv{a} \ensuremath{\circ}\xspace \ptv{b}}}{\sem{ }}{\syncat{\textit{A}}}}
\end{prooftree}
}
\parbox[t]{5cm}{
\ex\label{lseone} Backward Slash Elimination:\\[.5\baselineskip]
\begin{prooftree}
\NoSem
\hypo{\LexEnt{\pt{\ptv{b}}}{\sem{ }}{\syncat{\textit{B}}}}
\hypo{\LexEnt{\pt{\ptv{a}}}{\sem{ }}{\syncat{\textit{B}\ensuremath{\backslash}{}\textit{A}}}}
\infer2[\ensuremath{\backslash}E]{\LexEnt{\pt{\ptv{b} \ensuremath{\circ}\xspace \ptv{a}}}{\sem{ }}{\syncat{\textit{A}}}}
\end{prooftree}
}
\zl
```
While this does compile, the result is not as expected. The a. and b. come out somewhere below on the page:
![grafik](https://user-images.githubusercontent.com/4655859/119647795-fb57d380-be20-11eb-810c-70f04da07ddd.png)

**Comment by Glottotopia** [comment]
```
\newcommand{\shortbox}[3][-.7]{
    \parbox[t]{.4\textwidth}{
      \vspace{#1\baselineskip} #2\strut~~ #3}%
}

![Screenshot_2021-06-10_09-42-40](https://user-images.githubusercontent.com/1553576/121485157-37b63280-c9d0-11eb-8d10-f640504bb12f.png)
\ea
\begin{xlist}
\shortbox{a.}{abc}\shortbox{b.}{def}
\end{xlist}
\z

\ea
\begin{xlist}
\shortbox{a.}{ghi}\shortbox{b.}{jkl}
\end{xlist}
\z
```

**Comment by stefan11** [comment]
Yes, this is like having a table, isn't it? But the labels will not work for this. I cannot refer to (1a) and (1b) with the latex reference mechanism or can I?

**Comment by Glottotopia** [comment]
It has less overhead than a table.
you can use `(\ref{ex:mylabel}a)`

**Comment by Glottotopia** [comment]
you do not need the `{xlist}` parts actually

**Comment by Glottotopia** [comment]
```
\ea 
\shortbox{a.}{abc}\shortbox{b.}{def} 
\z

\ea 
\shortbox{a.}{ghi}\shortbox{b.}{jkl} 
\z
```

**Comment by Glottotopia** [comment]
BTW the backward Slash in 29b `\ I^n` has extra horizontal space after it as compared to both 28b and 29a

**Comment by stefan11** [comment]
But we need some tabular environment if the content spans more than one line, since the content should not start below a. and b. but below the first line of the second argument to shortbox (ghi or jkl).

**Comment by stefan11** [comment]
I did it this way now:
```latex
\newcommand{\twomulticolexamples}[2]{
\begin{tabular}[t]{@{}l@{~~}l@{\hspace{1em}}l@{~~}l@{}}
a. & \parbox[t]{.4\textwidth}{#1} & b. & \parbox[t]{.4\textwidth}{#2}\\
\end{tabular}
}
```
There was a version with multicols that worked: If multicols was used outside the exe environment. But for one example the examples were too big for multicols but OK for my table solution, so I used my table solution.
