### ISSUE TITLE
shift examples in proofs to the left and use the remaining space cg.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#159]
![grafik](https://user-images.githubusercontent.com/4655859/119524369-deb68f80-bd7d-11eb-921d-9a0396e7b25f.png)

**Comment by stefan11** [comment]
@Glottotopia you said, we should not mess around here. The proofs are shrunken in size. Some are really huge so that the font gets very small. The always extend downwards to the left. So we could use the space below the example number. Do you know how to do this, so that we can use the whole \textwidth? Shifting the space of the example number to the left and then scale to textwidth?

**Comment by Glottotopia** [comment]
```
\ea\hspace*{-1cm}\proof
\z
```

**Comment by stefan11** [comment]
\oneline did not get the new \linewidth after the shift. This is what I did:
\hspace{-2em}\attop{\resizebox{\linewidth+1.8em}{!}{\proof}
