### ISSUE TITLE
de / De for de Saussure in index

### ISSUE THREAD

**Issue by stefan11** [langsci/259#164]
<img width="208" alt="grafik" src="https://user-images.githubusercontent.com/4655859/120183169-a268b080-c20f-11eb-8243-7ca6cd840623.png">

bibtex seems to capitalize de if it is not in brackets. This applies to the index only.

**Comment by Glottotopia** [comment]
Makefile has a `sed` line for this (`\MakeCapital`).

**Comment by stefan11** [comment]
Yes, this did not work since there were entries with {de Saussure}. But I fixed this now.
