### ISSUE TITLE
too much space before an example maybe due to multicolumns (cg.tex)

### ISSUE THREAD

**Issue by stefan11** [langsci/259#170]
![grafik](https://user-images.githubusercontent.com/4655859/121480164-10a93200-c9cb-11eb-8c25-c18315bc9fd7.png)

There is too much space before (12).

**Comment by Glottotopia** [comment]
see https://github.com/langsci/259/issues/156

**Comment by stefan11** [comment]
OK. I will close this. But I need help with #156. The parbox solution does not work. I could use tabular, but then the labels do not work.
