### ISSUE TITLE
unicode characters in subject index are not sorted corrctly (Panini)

### ISSUE THREAD

**Issue by stefan11** [langsci/259#200]

**Comment by Glottotopia** [comment]
The "a" or the "n"?

**Comment by Glottotopia** [comment]
and why is Panini in the subject index? Should it not be the name index?

**Comment by stefan11** [comment]
The fixing script was not applied to the subject index.

**Comment by stefan11** [comment]
> and why is Panini in the subject index? Should it not be the name index?

The index item is Panini's Principle
