### ISSUE TITLE
Language information sometimes looks ugly (eg in complex-predicates.tex)

### ISSUE THREAD

**Issue by stefan11** [langsci/259#34]
![grafik](https://user-images.githubusercontent.com/4655859/90154771-d3641b80-dd8a-11ea-9f72-ea9aa22fde8b.png)

@Glottotopia Do you have a suggestion how to deal with this?

**Comment by stefan11** [comment]
@Glottotopia shall we ust drop this issue? Do not know how to improve this.

**Comment by Glottotopia** [comment]
Do not use right floating language labels in chapters where you have long examples. Put the language label in line by itself instead.
