### ISSUE TITLE
the distance between lines in figure captions is too short (example from morphology.tex)

### ISSUE THREAD

**Issue by stefan11** [langsci/259#42]
![grafik](https://user-images.githubusercontent.com/4655859/102885593-e501b200-4453-11eb-83d5-a044fefb0c3c.png)

**Comment by Glottotopia** [comment]
This is intentional and has been discussed before

**Comment by stefan11** [comment]
This is even worse. The letters touch each other:
![grafik](https://user-images.githubusercontent.com/4655859/106296849-74b82e80-6252-11eb-99bf-d40ae61c53b4.png)

in cxg.tex

**Comment by stefan11** [comment]
![Uploading grafik.png…]()

**Comment by stefan11** [comment]
Solved by dropping the caption package and reverting back to normal.
