### ISSUE TITLE
make caption longer for special cases?

### ISSUE THREAD

**Issue by stefan11** [langsci/259#47]
![grafik](https://user-images.githubusercontent.com/4655859/102906479-fb6c3580-4474-11eb-9d7b-3080ce571af4.png)

**Comment by Glottotopia** [comment]
Use  "Masc.sg forms ... " and it will fit the line. Other than that, every line has a fixed length, and if you go beyond, there will be a need for a line break. This line is no exception. 
I would also suggest to use `\begin{tabularx}{.8\textwidth}{XXl}`

**Comment by stefan11** [comment]
A similar problem here:
![grafik](https://user-images.githubusercontent.com/4655859/106304170-5145b180-625b-11eb-96ed-a4ef97eb8564.png)
What I am asking for is a onetime extension of the space the caption can take. Just make it the width of "7)" longer for this one occasion.

**Comment by stefan11** [comment]
![grafik](https://user-images.githubusercontent.com/4655859/109996519-986a0b00-7d0f-11eb-8695-6b0830c6abb7.png)

chapter udc.tex

**Comment by stefan11** [comment]
Solved by going back to old captions.
