### ISSUE TITLE
! does not work anylonger / brackets too large cxg.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#71]
![grafik](https://user-images.githubusercontent.com/4655859/106357122-74786b80-6304-11eb-9d91-d45652bc303e.png)

I used to use ! to avoid large brackets for things like `NP[\type{acc}]`, but now the ! is shown in the AVMs:

```latex
\avm{
	[\type*{reg-bar-adj}
	\punk{phon}{\1 \+ \phonliste{ bar }} \\
	\punk{morph-b}{<[\type*{trans-verb}
			  phon \; \1 \\
			  synsem|loc  [cat|comps & < NP ![\type{acc}]!\ind{2} > \+ \3 \\
			               cont|nuc  & \4 [act & index \\
			                               und & \2] ] ] >} \\
	synsem|loc &	[cat	[head  & adj \\
				 subj  & < NP\ind{2} > \\
				 comps & \3 ] \\
			 cont|nuc  [reln    & $\diamond$ \\
				    und     & \2 \\
				    soa-arg & \4 ] ] ]
}
```
![grafik](https://user-images.githubusercontent.com/4655859/106357158-a5f13700-6304-11eb-893a-fb56b731c412.png)

**Comment by kopeckyf** [comment]
Escaping the avm mode does not work if the current structure is within the scope of another command. Sorry about that. Here, escaping with `!` is done within an enclosing `\punk{}`. 

This is an instance of https://github.com/langsci/langsci-avm/issues/2

**Comment by stefan11** [comment]
Hm. And what do I do now? I guess having a way to not do alignment without punks would solve this.

Back in the old days a simple \\ without & was enough to do this.

**Comment by kopeckyf** [comment]
You can do different things:

- Remove the punks. Not clear to me why they are in use here anyway.
- Adjust the spacing of delimiters locally. You can use `\avmsetup` in the middle of an AVM. You can insert additional line breaks to make the code more readable in this case, e.g.: `< NP{\avmsetup{stretch=0.75}[\type{acc}]}>`. Note the grouping `{}` around the innermost structure, which protects `\avmsetup` to be applied locally.
- Accept the current output. In my tests on a unmodified `langsci-avm`, the spacing around _acc_ is tighter than in your screenshot. Maybe you changed the setup of `langsci-avm` somewhere in your document, e.g. by changing the values to `stretch`, `delimfall` or `delimfactor`?

**Comment by kopeckyf** [comment]
And of course you could wait until https://github.com/langsci/langsci-avm/issues/2 is solved.

**Comment by kopeckyf** [comment]
Here's a solution with `align=false`. Note you can't use the starred types in non-aligned AVMs (I will work on this)

```latex
\avm[align=false,vectorsep=1ex]{
	[\type{reg-bar-adj}\\
	phon & \1 \+ \phonliste{bar} \\
    morph-b & <[\type{trans-verb}\\
		phon & \1 \\
		synsem|loc & [cat|comps & < NP ![\type{acc}]!\ind{2} > \+ \3 \\
		              cont|nuc  & \4 [act & index \\
		              und & \2] ] ] > \\
	synsem|loc &	[cat &	[head  & adj \\
	                 subj  & < NP\ind{2} > \\
	                 comps & \3 ] \\
	cont|nuc  & [reln    & $\diamond$ \\
	             und     & \2 \\
	             soa-arg & \4 ] ] ]
}
```
