### ISSUE TITLE
hyphenation in caption is terrible minimalism.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#73]
![grafik](https://user-images.githubusercontent.com/4655859/106516556-7fcfc080-64d7-11eb-8a92-0f879a653b4f.png)

**Comment by Glottotopia** [comment]
`Cartographic\\`
Otherwise, there is not much you can do. You could be a bit more wordy, like "The treatment" or "Treatment of the structures of ..."

**Comment by stefan11** [comment]
> `Cartographic\\`
> Otherwise, there is not much you can do. You could be a bit more wordy, like "The treatment" or "Treatment of the structures of ..."

Ah, thanks. Yes, hardwired linebreaks is a good idea. But would it be possible to have a bit more space for a caption on a case by case baisis? So that it gets 2em more in the example at hand?
