### ISSUE TITLE
Argument Realization Principle in arg-st.tex

### ISSUE THREAD

**Issue by 1koenig1** [langsci/259#82]
WKD must mention in their ARG-ST chapter that the ARP is sometimes (most times these days?) understood to allow non-canonical synsems onto SUBJ and COMPS list (cf. work on so-called clitics in Romance and interaction of pro-drop and raising-- Anne Abeillé).

**Comment by stefan11** [comment]
@1koenig1 There is no ARP in your chapter or is there?

**Comment by stefan11** [comment]
The chapter has various places talking about ARG-ST mappings:

> "To summarize this section, while the relationship between ARG-ST, SUBJ, and COMPS lists was originally conceived as a straightforward one, enabling binding principles to maintain their simple form by defining ARG-ST as the concatena- tion of the other two, the relationship was soon loosened. Looser relationships between ARG-ST and the valence lists are invoked in accounts of several core syn- tactic phenomena. Arguments not realized overtly in their canonical positions due to extraction, cliticization, or pro-drop (null anaphora) appear on ARG-ST but not in any valence list. Accounts of syntactic ergativity in HPSG involve varia- tions in the mapping between ARG-ST and valence lists; in particular, the element of SUBJ is not, in such languages, the first element of ARG-ST. Modifications of ARG-ST play a role in some treatments of passivization, where its expected first element is suppressed, and in languages with multiple, symmetric objects, where a partial rather than total ordering of ARG-ST elements has been postulated (see Section 5.3 for details on the analysis of passives in HPSG). Thus ARG-ST has now acquired an autonomous status within HPSG, and is not merely a predictable re- arrangement of information present in the valence lists." 

And:
> A lexical sign whose ARG-ST list is just the concatenation of its SUBJ and COMPS lists conforms to the Argument Realization Principle (ARP); such signs are called canonical signs by Bouma et al. (2001). Non-canonical signs, which violate the ARP, have been approached in two ways. In one approach, a lexical rule takes as input a canonical entry and derives a non-canonical one by removing items from the valence lists, while adding an affix or designating an item as an unbounded dependent by placement on the SLASH list. In the other approach, a feature of each ARG-ST list item specifies whether the item is subject to the ARP (hence mapped to a valence list), or ignored by it (hence expressed in some other way).

This is not addressing what Anne wanted: Even though objects are marked as non-cannonical they can appear on the SUBJ list.

We decided to postpone changed to the second edition.

**Comment by stefan11** [comment]
Other chapters in the handbook can be crossreferenced. Many chapter discuss it.
