### ISSUE TITLE
set does not seem to be possible in parallel to list in semantics.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/259#98]
![grafik](https://user-images.githubusercontent.com/4655859/109348219-881be100-7874-11eb-8429-d871e43a28aa.png)

```latex
\avm{
			[\type*{question}
			params & set!(param)!]
		}
```

**Comment by kopeckyf** [comment]
What's the problem here? The escape mode does not restore `\normalfont`.

You could define a custom command `\set`, analogously to `\list`.

**Comment by stefan11** [comment]
A name clash.

**Comment by kopeckyf** [comment]
Please provide a complete error message and MWE.
